import './globals.css'
import Navbar from '@/components/navbar'
import React from 'react'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Luminarias de alta eficiencia - Strom',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <main className={`${montserrat.className}`}>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
